/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.ActionListener;
import javax.swing.BorderFactory;
import javax.swing.JButton;

/**
 * Controla los parámetros de la ventana principal. La clase establece los
 * ActionListener y sus métodos. 
 * @version 1.1
 * @author DeniseGT
 */
public class FPrincipal extends javax.swing.JFrame {

    /**
     * Asigna el ActionListener a los botones de la ventana. Este ActionListener permitirá realizar 
     * la relación entre la interfaz gráfica y el control de la aplicación.
     *
     * @param oidor 
     * @see Control.CFPrincipal#actionPerformed(java.awt.event.ActionEvent) 
     */
    public void setOidor(ActionListener oidor) {
        JButton[] botons = {Bnumerología, baleatorio, bcerrar};
        for (JButton boton : botons) {
            boton.addActionListener(oidor); // A todo los bototnes, realizamos el action listener // V-C
        }
    }

    /**
     * Creates new form FPrincipal. La ventana estará centrada en la pantalla.
     */
    public FPrincipal() {
        initComponents();
        setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        bcerrar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        Bnumerología = new javax.swing.JButton();
        baleatorio = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        texto = new javax.swing.JLabel();
        bcolor = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setIconImage(getIconImage());
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(173, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bcerrar.setText("Cerrar");
        bcerrar.setActionCommand("bcerrar");
        bcerrar.setFocusable(false);
        jPanel1.add(bcerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 520, 140, 40));

        jLabel1.setFont(new java.awt.Font("Monospaced", 1, 45)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText(" CALCULADORA DE NOMBRES ");
        jLabel1.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(255, 255, 255)));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, 675, 70));

        Bnumerología.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Bnumerología.setText("NUMEROLOGÍA");
        Bnumerología.setActionCommand("Bnumerología");
        Bnumerología.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)));
        Bnumerología.setFocusable(false);
        Bnumerología.setOpaque(true);
        Bnumerología.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BnumerologíaActionPerformed(evt);
            }
        });
        jPanel1.add(Bnumerología, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 290, 247, 126));

        baleatorio.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        baleatorio.setText("ALEATORIO");
        baleatorio.setActionCommand("baleatorio");
        baleatorio.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)));
        baleatorio.setFocusable(false);
        baleatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                baleatorioActionPerformed(evt);
            }
        });
        jPanel1.add(baleatorio, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 290, 247, 127));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Calcular-numerologia-nome-completo.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 840, 430));

        texto.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        texto.setText("¡");
        texto.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                textoPropertyChange(evt);
            }
        });
        jPanel1.add(texto, new org.netbeans.lib.awtextra.AbsoluteConstraints(106, 164, 650, 110));

        bcolor.setBackground(new java.awt.Color(173, 204, 204));
        bcolor.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bcolor.setText("¡Cambia el color!");
        bcolor.setActionCommand("bcolor");
        bcolor.setOpaque(true);
        bcolor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bcolorActionPerformed(evt);
            }
        });
        jPanel1.add(bcolor, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 520, 168, 56));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bcolorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bcolorActionPerformed
        // TODO add your handling code here:
        
        if (bcolor.isSelected()) {
            jPanel1.setBackground(new Color(255, 182, 193));
            bcolor.setBackground(new Color(255, 182, 193));

        } else {
            jPanel1.setBackground(new Color(173, 204, 204));
            bcolor.setBackground(new Color(173, 204, 204));

        }
    }//GEN-LAST:event_bcolorActionPerformed

    private void textoPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_textoPropertyChange
        // TODO add your handling code here:
        String t = "<html><body><b>¡Bienvenido a nuestra calculadora de nombres! </b> Aquí podrás averiguar el significado de tu nombre pulsando en <b> \"numerología\" </b> u obtener un nombre al azar pulsando  <b> \"aleatorio\"  </b> <br> </body></html>";
        texto.setText(t);
    }//GEN-LAST:event_textoPropertyChange

    private void baleatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_baleatorioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_baleatorioActionPerformed

    private void BnumerologíaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BnumerologíaActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_BnumerologíaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Bnumerología;
    private javax.swing.JButton baleatorio;
    private javax.swing.JButton bcerrar;
    private javax.swing.JRadioButton bcolor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel texto;
    // End of variables declaration//GEN-END:variables

    /**
     * Cambia el icono de la ventana. La imagen se situa en el paquete
     * "imagenes".
     * @see imagenes
     */
    @Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().
                getImage(ClassLoader.getSystemResource("imagenes/743crystalball1_100391(1).png"));

        return retValue;
    }
}
