/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.ActionListener;
import javax.swing.JButton;

/**
 * Controla los parámetros de la ventana principal. La clase establece los
 * ActionListener y sus métodos.
 *
 * @version 1.1
 * @author DeniseGT
 */
public class Numerología extends javax.swing.JFrame {

    /**
     * Asigna el ActionListener a los botones de la ventana. Este ActionListener
     * permitirá realizar la relación entre la interfaz gráfica y el control de
     * la aplicación.
     *
     * @param oidor
     * @see Control.CNumerología#actionPerformed(java.awt.event.ActionEvent)
     */
    public void setOidor(ActionListener oidor) {
        bEnviarNombre.addActionListener(oidor);
        cSaberMás.addActionListener(oidor);
        bvolver.addActionListener(oidor);
    }

    /**
     * Creates new form Numerología. La ventana estará centrada en la pantalla.
     */
    public Numerología() {
        initComponents();
        setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        texto2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        texto1 = new javax.swing.JLabel();
        jTuNombre = new javax.swing.JTextField();
        texto3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tarea = new javax.swing.JTextArea();
        cSaberMás = new javax.swing.JCheckBox();
        bEnviarNombre = new javax.swing.JButton();
        bvolver = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        setPreferredSize(new java.awt.Dimension(900, 800));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(173, 204, 204));

        jLabel1.setFont(new java.awt.Font("Monospaced", 1, 45)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Significado de tu nombre");
        jLabel1.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(255, 255, 255)));

        texto2.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        texto2.setText("El significado es:");
        texto2.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                texto2PropertyChange(evt);
            }
        });

        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));

        texto1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        texto1.setText("jLabel2");
        texto1.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                texto1PropertyChange(evt);
            }
        });

        jTuNombre.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jTuNombre.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 182, 193), 2));

        texto3.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        texto3.setText("Introduce aquí tu nombre y apellidos:");
        texto3.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                texto3PropertyChange(evt);
            }
        });

        tarea.setColumns(20);
        tarea.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tarea.setRows(5);
        jScrollPane1.setViewportView(tarea);

        cSaberMás.setBackground(new java.awt.Color(173, 204, 204));
        cSaberMás.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        cSaberMás.setText("Saber más sobre la numerología");
        cSaberMás.setActionCommand("cSaberMás");
        cSaberMás.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cSaberMásActionPerformed(evt);
            }
        });

        bEnviarNombre.setText("Enviar");
        bEnviarNombre.setActionCommand("bEnviarNombre");
        bEnviarNombre.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        bvolver.setText("Volver");
        bvolver.setActionCommand("bvolver");
        bvolver.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(texto3)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jSeparator1)
                        .addComponent(texto2)
                        .addComponent(jTuNombre)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 686, Short.MAX_VALUE)
                        .addComponent(bEnviarNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 675, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(133, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(cSaberMás)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bvolver, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(81, 81, 81)
                    .addComponent(texto1, javax.swing.GroupLayout.PREFERRED_SIZE, 672, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(147, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(138, 138, 138)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(texto3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTuNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bEnviarNombre)
                .addGap(29, 29, 29)
                .addComponent(texto2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cSaberMás)
                    .addComponent(bvolver))
                .addContainerGap())
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(148, 148, 148)
                    .addComponent(texto1)
                    .addContainerGap(562, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void texto3PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_texto3PropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_texto3PropertyChange

    private void texto1PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_texto1PropertyChange
        // TODO add your handling code here:

        String t = "<html><body><b>El nombre y apellido</b> de una persona puede determinar muchas cosas sobre la  personalidad y la misión de la misma en el mundo. <b> Y gracias a la numerología se puede conocer un poco más  sobre todo esto. </b></body></html>";
        texto1.setText(t);
    }//GEN-LAST:event_texto1PropertyChange

    private void texto2PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_texto2PropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_texto2PropertyChange

    private void cSaberMásActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cSaberMásActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cSaberMásActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Numerología.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Numerología.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Numerología.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Numerología.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Numerología().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bEnviarNombre;
    private javax.swing.JButton bvolver;
    private javax.swing.JCheckBox cSaberMás;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTuNombre;
    private javax.swing.JTextArea tarea;
    private javax.swing.JLabel texto1;
    private javax.swing.JLabel texto2;
    private javax.swing.JLabel texto3;
    // End of variables declaration//GEN-END:variables

    /**
     * Obtiene el texto de un TextField.
     *
     * @return String, donde se situará el nombre de la persona.
     */
    public String dameElTexto() {
        return jTuNombre.getText();
    }

    /**
     * Le llega un texto y lo muestra un texto en el TextArea.
     * @param texto
     */
    public void muestra(String texto) {
        tarea.setText(texto);
    }

    /**
     * Le llega un texto y lo borra en el TextField. Realmente no lo borra, si no que lo sustituye por un String 
     * donde no hay nada ("").
     * @param texto 
     */
    public void borraElTexto(String texto) {
        jTuNombre.setText("");
    }

    /**
     * Cambia el icono de la ventana. La imagen se situa en el paquete
     * "imagenes".
     *
     * @see imagenes
     */
    @Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().
                getImage(ClassLoader.getSystemResource("imagenes/743crystalball1_100391(1).png"));

        return retValue;
    }
}
